import{createRouter,createWebHistory}from'vue-router'
const routes=[
{
path:'/',
name:'Dashboard',
component:()=>import('@/views/Dashboard.vue'),
meta:{requiresAuth:true}
},
{
path:'/discover',
name:'Discover',
component:()=>import('@/views/Discover.vue'),
meta:{requiresAuth:true}
},
{
path:'/project/:id',
name:'Project',
component:()=>import('@/views/ProjectDetail.vue'),
meta:{requiresAuth:true}
},
{
path:'/invest',
name:'Invest',
component:()=>import('@/views/Invest.vue'),
meta:{requiresAuth:true}
},
{
path:'/portfolio',
name:'Portfolio',
component:()=>import('@/views/Portfolio.vue'),
meta:{requiresAuth:true}
},
{
path:'/rewards',
name:'Rewards',
component:()=>import('@/views/Rewards.vue'),
meta:{requiresAuth:true}
},
{
path:'/verification',
name:'Verification',
component:()=>import('@/views/Verification.vue'),
meta:{requiresAuth:false}
},
{
path:'/admin',
name:'Admin',
component:()=>import('@/views/Admin.vue'),
meta:{requiresAuth:true,requiresAdmin:true}
},
{
path:'/login',
name:'Login',
component:()=>import('@/views/Login.vue'),
meta:{requiresAuth:false}
}
]
const router=createRouter({
history:createWebHistory(),
routes
})
router.beforeEach((to,from,next)=>{
const authStore=useAuthStore?.()
if(to.meta.requiresAuth&&!authStore?.isAuthenticated){
next('/login')
}else if(to.meta.requiresAdmin&&!authStore?.user?.isAdmin){
next('/')
}else{
next()
}
})
export default router
